### ISSUE TITLE
Overriding user mouse while recorded event is playing

### ISSUE THREAD

**Issue by ShayRubach** [Alien-AV/macro_record#1]
<b>Issue:</b><br>User can move mouse while recorded event is playing and sync-out the recorded event.<br>

#### How to replicate:
1. Record an event
2. Play it
3. While event is playing, move the mouse.

**Comment by Alien-AV** [comment]
- need to add configuration for this - need to make a configuration window? for starters can just make a checkbox on main screen
- block user input? how? maybe just use absolute coordinates for everything?

**Comment by Alien-AV** [comment]
worked-around in 81e677bc0a86d40e3c151c47f0cf0ec33827b2aa - it's possible to convert the mouse events to use absolute positioning, and thus the pointer will trace it's absolute path
the relative movement is still important to keep, as it makes it possble, for example, to reproduce the same mouse gesture with a different starting spot
