### ISSUE TITLE
"stop recording" hotkey is partly recorded itself

### ISSUE THREAD

**Issue by Alien-AV** [Alien-AV/macro_record#11]
When pressing ctrl+w to stop recording, the "press ctrl" event is recorded, but "release ctrl" event isn't - after using this hotkey the event needs to be deleted manually or it gives effect of a sticky ctrl key.
In similar manner, "release ctrl" and "release q" are always recorded in start of macro.

**Comment by ShayRubach** [comment]
close this due to #12 fixed?

**Comment by Alien-AV** [comment]
Depends on whether we want the keypress to not show up in the macro as well.
I guess we'll close it for now, as the real issue is resolved, and we'll fix the UX issue of extra keys in the macro, when it actually bugs someone.
Fixed in 36e3efefd41c6f4300844812d982e686e3d92405
