### ISSUE TITLE
When replaying macro and not letting go of ctrl key fast enough, ctrl is applied to kbd input

### ISSUE THREAD

**Issue by Alien-AV** [Alien-AV/macro_record#12]
When replaying the macro through ctrl+e hotkey, if delays between events are low enough, replay applies ctrl to the keyboard input. (Issue partly mitigated by issue #11)

Probably need to check what keys are pressed at the moment of start of playback, and send an event to release them - and then inject the macro itself. Should happen behind the scenes as it's not pretty for the user to see extraneous events in his macro.

**Comment by ShayRubach** [comment]
So, after Play() is invoked, u want to (pseudo) check if(GetKey.KeyDown(KeyCode.Ctrl)) and then ignore it to fill the gap between key hold and release? @Alien-AV

**Comment by Alien-AV** [comment]
Yep, but actually need to create and inject a KeyboardEvent{ KeyCode=Ctrl, KeyUp=true } at the very start of playback, since there's no way to ignore the pressed key afterwards. It's because the only thing we control "playback-wise" is simulating new keyboard key presses, we don't actually hook between the keyboard and the windows input system, and we can't "drop" real keyboard/mouse events.

(Actually Windows hook API which we use in CaptureEngine is able to intercept and drop real keyboard events AFAIK, but then it will be dropping the simulated events as well...)
