### ISSUE TITLE
implement an events wrapper class around the protobuf InputEvent class

### ISSUE THREAD

**Issue by Alien-AV** [Alien-AV/macro_record#23]
- put protobuf-generated class in namespace
- wrap access to the parsed protobuf object fields in a new class, limit exposure of protobuf API
- implement PropertyChanged event listeners on the new class for better integration with ObservableCollection

**Comment by ShayRubach** [comment]
You wish to wrap ProtobufGenerated.InputEvent / ProtobufGenerated.InputEvent**s** only for the c# side usage right?

**Comment by Alien-AV** [comment]
Yeah, only the C# side. Currently InputEvent gives too much functionality, which should be hidden, and lacks some functionality (PropertyChanged event listeners), which can be implemented in the wrapper class.

**Comment by Alien-AV** [comment]
fixed in b22cccbcd57025faa25c8a981387dc8698e900fe
