### ISSUE TITLE
Enter keystroke not recording

### ISSUE THREAD

**Issue by Stolyassa** [Alien-AV/macro_record#40]
Hello, I want to record a list of keystrokes incloding enter key inside. But as soon as I press enter key while recording all the other recordigs are being deleted. It is impossible to use enter key inside a macro.

**Comment by Alien-AV** [comment]
Thanks for the report.

Is it possible that your keystrokes include pressing "tab"?
It may be that you're focusing the "start recording" or "stop recording" button inside the app by tabbing, and then pressing enter invokes that button.

If that is the case, I believe that I'll just disable the standard keybindings (tab and enter for example) while recording. Or maybe disable them fully.

Meanwhile you can try focusing a different window before pressing the keys.

**Comment by Alien-AV** [comment]
closing due to lack of public interest
